# Generated by Django 4.1.5 on 2024-12-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del examen médico', max_length=200, unique=True)),
                ('descripcion', models.TextField(help_text='Descripción detallada del examen y su propósito')),
                ('preparacion', models.TextField(blank=True, help_text='Indicaciones para la preparación previa al examen', null=True)),
                ('duracion_aproximada', models.PositiveIntegerField(help_text='Duración aproximada del examen en minutos')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio estimado del examen', max_digits=10)),
                ('fecha_disponible', models.DateField(help_text='Fecha a partir de la cual el examen está disponible')),
                ('categoria', models.CharField(choices=[('laboratorio', 'Laboratorio'), ('imagen', 'Imagenología'), ('especial', 'Especializado'), ('otros', 'Otros')], default='otros', help_text='Categoría del examen', max_length=100)),
                ('recomendaciones_post_examen', models.TextField(blank=True, help_text='Cuidados o indicaciones después del examen', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, help_text='Última fecha de modificación del registro')),
            ],
        ),
    ]
