# Generated by Django 4.1.5 on 2024-12-24 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0002_libro_delete_examenes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='description',
            new_name='descripcion',
        ),
    ]
