# Generated by Django 5.1.4 on 2025-01-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0003_rename_description_libro_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='imagen',
        ),
        migrations.AddField(
            model_name='libro',
            name='archivo',
            field=models.FileField(null=True, upload_to='archivos/', verbose_name='Archivo'),
        ),
    ]
