# Generated by Django 5.1.4 on 2025-01-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0004_remove_libro_imagen_libro_archivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='descripcion',
            new_name='cod_fonasa',
        ),
        migrations.AddField(
            model_name='libro',
            name='plazo_entrega',
            field=models.TextField(null=True, verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='libro',
            name='preparacion',
            field=models.TextField(null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.FileField(null=True, upload_to='archivos2/', verbose_name='Archivo2'),
        ),
    ]
