# Generated by Django 5.1.4 on 2025-01-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0005_rename_descripcion_libro_cod_fonasa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='plazo_entrega',
            field=models.TextField(null=True, verbose_name='preparacion'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='preparacion',
            field=models.TextField(null=True, verbose_name='preparacion'),
        ),
    ]
