# Generated by Django 5.1.4 on 2025-01-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0006_alter_libro_plazo_entrega_alter_libro_preparacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='plazo_entrega',
            field=models.TextField(null=True, verbose_name='plazo entrega'),
        ),
    ]
