# Generated by Django 5.1.4 on 2025-01-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0007_alter_libro_plazo_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='cod_fonasa',
            field=models.TextField(null=True, verbose_name='codigo fonasa'),
        ),
    ]
