# Generated by Django 5.1.4 on 2025-01-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0008_alter_libro_cod_fonasa'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='tipo_examen',
            field=models.TextField(null=True, verbose_name='Tipo examen'),
        ),
    ]
