# Generated by Django 5.1.4 on 2025-01-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0009_libro_tipo_examen'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='instruccion_paciente',
            field=models.FileField(null=True, upload_to='instruccionpaciente/', verbose_name='instruccion a paciente'),
        ),
    ]
