# Generated by Django 5.1.4 on 2025-01-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0010_libro_instruccion_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='titulo',
        ),
        migrations.AlterField(
            model_name='libro',
            name='instruccion_paciente',
            field=models.FileField(blank=True, null=True, upload_to='instruccionpaciente/', verbose_name='instruccion a paciente'),
        ),
    ]
