# Generated by Django 5.1.4 on 2025-01-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0011_remove_libro_titulo_alter_libro_instruccion_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='fecha',
            field=models.TextField(null=True, verbose_name='fecha'),
        ),
    ]
