# Generated by Django 5.1.4 on 2025-01-17 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0012_libro_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='fecha',
        ),
    ]
