# Generated by Django 5.1.4 on 2025-01-31 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0015_rutina_registroejercicio_nota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroejercicio',
            name='rutina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='gymapp.rutina'),
        ),
        migrations.CreateModel(
            name='SerieEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeticiones', models.IntegerField()),
                ('nota', models.TextField(blank=True, null=True)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_ejercicio', to='gymapp.registroejercicio')),
            ],
        ),
    ]
