# Generated by Django 5.1.4 on 2025-01-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0016_alter_registroejercicio_rutina_serieejercicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroejercicio',
            name='nota',
        ),
        migrations.RemoveField(
            model_name='registroejercicio',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='registroejercicio',
            name='repeticiones',
        ),
        migrations.AddField(
            model_name='serieejercicio',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
