# Generated by Django 5.1.4 on 2025-01-31 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0017_remove_registroejercicio_nota_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serieejercicio',
            name='registro',
        ),
        migrations.RemoveField(
            model_name='rutina',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeticiones', models.PositiveIntegerField()),
                ('notas', models.TextField(blank=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp.ejercicio')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='gymapp.rutina')),
            ],
        ),
        migrations.DeleteModel(
            name='RegistroEjercicio',
        ),
        migrations.DeleteModel(
            name='SerieEjercicio',
        ),
    ]
