# Generated by Django 5.1.4 on 2025-01-31 17:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0018_remove_serieejercicio_registro_remove_rutina_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre del ejercicio'),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre de la rutina'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='ejercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp.ejercicio', verbose_name='Ejercicio'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='repeticiones',
            field=models.PositiveIntegerField(verbose_name='Repeticiones'),
        ),
    ]
