# Generated by Django 5.1.4 on 2025-01-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0019_rutina_fecha_alter_ejercicio_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='serie_numero',
            field=models.PositiveIntegerField(default=1, verbose_name='Número de Serie'),
        ),
    ]
