# Generated by Django 5.1.4 on 2025-01-31 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0020_serie_serie_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='notas',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='serie_numero',
        ),
        migrations.AddField(
            model_name='serie',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='peso',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='serie',
            name='ejercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp.ejercicio'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='repeticiones',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='serie',
            name='rutina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp.rutina'),
        ),
    ]
