# Generated by Django 5.1.4 on 2025-02-05 11:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0023_usuario_alter_serie_numero_serie_serie_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
