# Generated by Django 5.1.4 on 2025-02-11 12:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0024_serie_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='numero_serie',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
